### ISSUE TITLE
Windows 10 support

### ISSUE THREAD

**Issue by euglv** [karthikeyankc/swoopy#1]
This script does not work on Windows 10 64-bit and Chrome 58.0.3029.110 (64-bit)
I am getting the following error:
```
  File "Swoopy.py", line 23, in <module>
    pwd = win32crypt.CryptUnprotectData(pwd, None, None, None, 0) #This returns a tuple description and the password
pywintypes.error: (-2146893813, 'CryptProtectData', 'Key not valid for use in specified state.')
```
But script still works on Windows 7 32bit and latest chrome.

**Comment by karthikeyankc** [comment]
This might be due to the way your user account is set in Windows 10. I'm on a W10 64-bit, and it works fine for me. As the chrome db is encrypted by the Windows' CryptProtecData, any script that uses it should be run with admin privileges. If it's a local account, try switching to the administrator account.

**Comment by euglv** [comment]
It is failing for built-in `Administrator` account. 
When I created a new non-administrator user on the same PC and stored some password in Chrome for that user - script showed it.
So script is failing only for built-in `Administrator` account, running script "As administrator" does not help. Actually, UAC dialog is never shown for Administrator account, all actions that require administrator privileges are working without running them "as administrator".

**Comment by karthikeyankc** [comment]
I hope you have installed the correct version of pywin32 on your administrator account. Other than that, at the moment, I have no clue.

**Comment by euglv** [comment]
The issue was in my profile, not in Windows.
SQLite table with passwords can have more entries, than is shown in Chrome settings. There were about 50 rows in SQLite table, but Chrome displayed about 15 passwords stored.
This happened because I copied my chrome profile from one machine to another several times, during upgrades and Windows re-installs. 
To fix your script - password extraction procedure should not stop after failing to decrypt some record from SQLite table, it should continue with the next record in that case.
