### ISSUE TITLE
Ubuntu 

### ISSUE THREAD

**Issue by SasiKiranK** [karthikeyankc/swoopy#2]
Hi 

I am unable to use in Ubuntu system
following error comes.
Traceback (most recent call last):
  File "Swoopy.py", line 3, in <module>
    import win32crypt
ImportError: No module named win32crypt

Thanks

**Comment by karthikeyankc** [comment]
The pywin32 package is for Windows. You can't use it on Ubuntu!

**Comment by SasiKiranK** [comment]
Hi Karthick
Can you migrate this code for Ubuntu as well ?

**Comment by karthikeyankc** [comment]
I would like to do that soon! :) But not at the moment!

You can try this:
```
$ sqlite3 ~/.config/google-chrome/Default/Login\ Data
$ sqlite> .output chrome-passwords.txt
$ sqlite> select origin_url, username_value, password_value from logins;
$ sqlite> .exit
```

More - https://productforums.google.com/forum/?hl=en#!category-topic/chrome/give-feature-feedback-and-suggestions/V_dcZEMlo80

The fields may vary!
