### ISSUE TITLE
Key not valid for use in specified state

### ISSUE THREAD

**Issue by l3oxy** [karthikeyankc/swoopy#4]
*OS: Windows 7 x64 (in a virtual machine)*
*Python: 2.7.15*

Running Swoopy on a 'Login Data' file from a different computer results in the below error. 
This is the same error as issue #1 , but after reading the entirety of that issue I am not aware of how to resolve this.

```
Traceback (most recent call last):
  File "C:\Users\Test\code\Swoopy-master\Swoopy-master\Swoopy.py", line 23, in <module>
    pwd = win32crypt.CryptUnprotectData(pwd, None, None, None, 0) #This returns a tuple description and the password
error: (-2146893813, 'CryptProtectData', 'Key not valid for use in specified state.')
```

Does anyone know if there is a way to augment Swoopy so that it can work on a foreign 'Login Data' file (i.e. one captured from a previous computer)? 

The credentials for the foreign Windows box are known, but I am unsure how to hard-code them into Swoopy to get past this error.

**Comment by karthikeyankc** [comment]
CryptUnProtectData API uses a key generated with your current credentials for the decryption. Unless you have the master key generated by the DPAPI from that foreign windows box of yours, I don't think you can decrypt it.

**Comment by l3oxy** [comment]
Hello @karthikeyankc , thank you for the rapid response.

It sounds like you are saying that both the credentials/passphrase __and the computer__ are together used to create the keys, and thus decryption requires the credentials and the original computer. 
Is that correct?

**Comment by l3oxy** [comment]
Please disregard my previous message.
I found the following Microsoft documentation which explained why this error was occurring for me:

https://docs.microsoft.com/en-us/windows/desktop/api/dpapi/nf-dpapi-cryptunprotectdata
> The CryptUnprotectData function decrypts and does an integrity check of the data in a DATA_BLOB structure. Usually, the only user who can decrypt the data is a user with the same logon credentials as the user who encrypted the data. __In addition, the encryption and decryption must be done on the same computer__. For information about exceptions, see the Remarks section of CryptProtectData.

@karthikeyankc , I believe this is exactly what you were saying. Thank you, you have helped me learn something new.
I recommend that this Microsoft requirement be documented in Swoopie's "_README.md_" file.
